services:
  traefik:
    image: traefik:v3
    restart: always
    command:
      - "--api.dashboard=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.network=public"
      - "--providers.docker.exposedbydefault=false"
      #- "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.traefikresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.traefikresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.traefikresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.traefikresolver.acme.email=levimenezes.thz@gmail.com" # Substitua pelo seu email
      - "--certificatesresolvers.traefikresolver.acme.storage=/traefikresolver/acme.json"
      - "--log.level=WARN"
      - "--log.format=common"
      - "--log.filePath=/etc/traefik/log/traefik/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/etc/traefik/log/traefik/access-log"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "certificates:/traefikresolver"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "config:/etc/traefik/"
      #- "./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml" # Monta o arquivo de configuração dinâmica
    networks:
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.exceler.tec.br`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=traefikresolver"
      - "traefik.http.routers.traefik-dashboard.service=traefik-dashboard"
      - "traefik.http.routers.traefik-dashboard.middlewares=redirect@docker"
      - "traefik.http.routers.traefik-dashboard.priority=1"
      # - "traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth@file" # Descomente para ativar autenticação

networks:
  external:
    external: true
    name: external

volumes:
  certificates:
    external: true
    name: certificates
  config:
    external: true
    name: config
